name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore tools
      run: dotnet tool restore
    
    - name: Build
      run: make build
    
    - name: Run tests
      run: make test
    
    - name: Check formatting
      run: make lint